{
 "title": "Cisco Catalyst 9800 - Clients stats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Logo",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<p style=\"text-align: center\">\n<img height=\"50\" src=\"https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Cisco_logo_blue_2016.svg/langfr-560px-Cisco_logo_blue_2016.svg.png\">\n</p>"
   }
  },
  {
   "title": "Download",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"devnet\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-wireless-client-oper:client-oper-data/traffic-stats\" or r[\"_measurement\"] == \"Cisco-IOS-XE-wireless-access-point-oper:access-point-oper-data/ethernet-if-stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_tx\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Download",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"devnet\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-wireless-client-oper:client-oper-data/traffic-stats\" or r[\"_measurement\"] == \"Cisco-IOS-XE-wireless-access-point-oper:access-point-oper-data/ethernet-if-stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_tx\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Upoad",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"devnet\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-wireless-client-oper:client-oper-data/traffic-stats\" or r[\"_measurement\"] == \"Cisco-IOS-XE-wireless-access-point-oper:access-point-oper-data/ethernet-if-stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_rx\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"devnet\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-wireless-client-oper:client-oper-data/traffic-stats\" or r[\"_measurement\"] == \"Cisco-IOS-XE-wireless-access-point-oper:access-point-oper-data/ethernet-if-stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_rx\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Clients" } },
   "targets": [
    {
     "query": "from(bucket: \"devnet\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-wireless-mobility-oper:mobility-oper-data/wlan-client-limit\")\n  |> filter(fn: (r) => r[\"_field\"] == \"curr_clients_count\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Current clients",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Clients" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"devnet\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-wireless-mobility-oper:mobility-oper-data/wlan-client-limit\")\n  |> filter(fn: (r) => r[\"_field\"] == \"curr_clients_count\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Max clients",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Clients" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "from(bucket: \"devnet\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-wireless-mobility-oper:mobility-oper-data/wlan-client-limit\")\n  |> filter(fn: (r) => r[\"_field\"] == \"curr_clients_count\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}