{
 "title": "Cisco Meraki",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Logo",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<p style=\"text-align: center\">\n<img height=\"50\" src=\"https://meraki.cisco.com/wp-content/uploads/2020/04/cisco-meraki-logo.png\">\n</p>"
   }
  },
  {
   "title": "Download",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "query": "from(bucket: \"devnet\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"meraki\")\n  |> filter(fn: (r) => r[\"_field\"] == \"downloadKbytes\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Download",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"devnet\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"meraki\")\n  |> filter(fn: (r) => r[\"_field\"] == \"downloadKbytes\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Upoad",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"devnet\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"meraki\")\n  |> filter(fn: (r) => r[\"_field\"] == \"uploadKbytes\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "query": "from(bucket: \"devnet\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"meraki\")\n  |> filter(fn: (r) => r[\"_field\"] == \"uploadKbytes\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "PoE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"devnet\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"meraki\")\n  |> filter(fn: (r) => r[\"_field\"] == \"poeUsage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Last PoE",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"devnet\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"meraki\")\n  |> filter(fn: (r) => r[\"_field\"] == \"poeUsage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}